runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /style
  static_dir: templates/style

- url: /.*
  script: main.app
  login: optional
- url: /stylesheet
  static_dir: templates/style

libraries:
- name: jinja2
  version: latest
- name: webapp2
  version: "2.5.2"
