runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /style
  static_dir: templates/style

<<<<<<< HEAD
=======

>>>>>>> 9bb9e3faa470d64de24a17128bdb3114d80269d3
- url: /.*
  script: main.app
  login: optional

libraries:
- name: jinja2
  version: latest
- name: webapp2
  version: "2.5.2"
